### ISSUE TITLE
Support token backup

### ISSUE THREAD

**Issue by chshersh** [rkaippully/gamgee#5]
When you accidentally lost your phone with installed Google Authenticator in there, you lost all your data and GoogleAuth doesn't have backup :(

It will be really good to support backup in `gamgee`. For example, if I could store encrypted file with all my keys anywhere I think is secure and robust place, it will be really good. But those things to achieve `gamgee` should support `backup` command or something like that.

**Comment by vmoti** [comment]
Why should `gamgee` provide a backup command when you can copy the contents of `~/.config/gamgee`. At the moment it's a single JSON file in there that can be backed up via your regular backup process. What am I missing?

**Comment by chshersh** [comment]
@vmoti I don't see this file mentioned in README.md. Probably you could add to documentation name of file where keys are stored. So everyone then can do copy in a way they like.

**Comment by vmoti** [comment]
That's a good suggestion. Since the project has been public for less than a week, I'm sure it'll be documented soon. See https://github.com/rkaippully/gamgee/blob/87ba29549bcd682cacf6d45346eb80e8110912a7/src/Gamgee/Token.hs#L121-L126

A future proof solution would be if you could run `gamgee path config` or similar to get the absolute path of the file or `gamgee info config-dir` and use that in your backup scripts. That way, the path could change.

**Comment by rkaippully** [comment]
This is very delayed but I have added an info command in f253607 that works like this:

```
$ gamgee info | jq .
{
  "config": {
    "filepath": "/Users/raghu/.config/gamgee/tokens.json",
    "version": 1
  },
  "version": "1.0.0"
}
```

For this specific issue, you can run:
```
$ gamgee info | jq .config.filepath
"/Users/raghu/.config/gamgee/tokens.json"
```
and backup that file.

**Comment by chshersh** [comment]
@rkaippully Thanks! That resolves my issue :slightly_smiling_face:
